services:
  db:
    image: postgres:15-alpine
    container_name: user_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gateway-service:
    build:
      context: ../
      dockerfile: ./services/gateway/Dockerfile
    container_name: gateway_service
    ports:
      - "8080:8080"
    environment:
      - PORT=:8080
      - USER_SVC_URL=user-service:50051
    depends_on:
      - user-service

  user-service:
    build:
      context: ../
      dockerfile: ./services/user/Dockerfile
    container_name: user_service
    ports:
      - "50051:50051"
    environment:
      - GRPC_PORT=:50051
      - DATABASE_URL=postgres://user_admin:secretpassword@db:5432/user_service_db?sslmode=disable
      - LOG_LEVEL=DEBUG
    depends_on:
      - db

volumes:
  postgres_data:
